apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "helloNest.fullname" . }}
  labels: {{ include "helloNest.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "helloNest.fullname" . }}
  minReplicas: {{ .Values.replica.min }}
  maxReplicas: {{ .Values.replica.max }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
